### ISSUE TITLE
Disable collision of ents and leaves

### ISSUE THREAD

**Issue by lightonflux** [minetest-LOTT/Lord-of-the-Test#16]
Other games like carbone have collisions with leaves disabled (for the player). So the player falls through them. Which is kind of realistic.

Ents have big problems to move around, because the vegetation is so dense and they collide with everything. 

I think it would help if they wouldn't collide with leaves but just walk through them.

**Comment by Amaz1** [comment]
There are three things that could be done here:
1. Your idea could be done. (This would involve quite a lot of work..)
2. The collision box could be made smaller, so the ent can move around more easily. This would probably end up with it looking like ents could move through trees... (Pretty easy, but a fair bit of tweaking.)
3. The ents could be made smaller. (The easiest of the lot.)

I'll probably go with 2, unless you think 3 would be better. If neither of those work out, I'll try 1.

**Comment by lightonflux** [comment]
My preference is 2-1-3. Favourite on the left, least favourite on the right.

**Comment by Amaz1** [comment]
This *should* fix the issue: https://github.com/minetest-LOTT/Lord-of-the-Test/commit/31ff3d8dfc5de51c58f1b2d25d6a316eb79b4533
It's not perfect, but it is a lot better than it was before...
If you don't think it is good enough, feel free to reopen this issue.
