### ISSUE TITLE
NPCs can't jump 

### ISSUE THREAD

**Issue by lightonflux** [minetest-LOTT/Lord-of-the-Test#17]
NPCs like elves and guards of gondor have big problems to jump in stable. And it looks like their timing is very bad and then they get stuck in a loop when they try to jump up on a node.

In the recent git version i never saw NPC even trying to jump. 

Is the because of recode the NPC or is that a regression?

**Comment by Amaz1** [comment]
npcf is going to be removed pretty soon, so I'm closing this.

I think that this has something to do with the minetest engine, as nothing has changed in the latest git concerning npcf..
