### ISSUE TITLE
Unkown Items (Orc Draught) appear in Orc Chests

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest-LOTT/Lord-of-the-Test#18]
Currently Strong Orc Draught and Weak Orc Draught appear in Orc Chests, but they are listed as Unknown Items.

I encountered this issue when playing the game recently. I entered and Orc Tower in the Mordor biome, got to the top and took the contents of all of the Orc Chests. Within the Orc Chests were a few different objects, however I noticed that two of the item stack I found were Unknown Items. I looked at my singleplayer file for the game and I noticed that the unknown item stacks were listed as "lottpotion:weakorcdraught" and "lottpotion:strongorcdraught".

Screenshot
![screenshot_1705253782](https://cloud.githubusercontent.com/assets/4276196/6093748/bb8807fe-aeda-11e4-845f-dc6294b04f6b.png)

**Comment by Amaz1** [comment]
There are quite a few unknown items in chests. I'll try to fix them tomorrow!

**Comment by Amaz1** [comment]
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/dd46f8227d41c859023765c9162446176dcd26e3
May be some unknown items, if you find them, please notify me.
