### ISSUE TITLE
When riding a horse the player's body goes through the horse

### ISSUE THREAD

**Issue by ExcaliburZero** [minetest-LOTT/Lord-of-the-Test#19]
Currently when you get on a horse and then go into third person view you see the player model going through the horse rather than riding the horse.

Screenshot
![screenshot_1729530405](https://cloud.githubusercontent.com/assets/4276196/6094984/47c7a52a-af13-11e4-8d13-8a4cdda26b9c.png)

**Comment by Amaz1** [comment]
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/25a8721daada241a0366ffb6fab4046bd0a5984a
Horses still aren't perfect, but that's largely to do with the engine...
