### ISSUE TITLE
Usage of tags

### ISSUE THREAD

**Issue by fishyWET** [minetest-LOTT/Lord-of-the-Test#21]
- If any error/ error related stuff > bug
- If any suggestion for improvements to be made > enchancement
- If bug affects gameplay or some other thing in a important way > High Priority
- If duplicate > duplicate
- If question > question
- If any suggestion for improvement as it is already on todo list/ fix or work for a particular feature is in progress > WIP
- If a unfixable bug (hopefully not)/ a feature assumed as a bug > wontfix
- If another stuff invalid to any of the following above (like this) > invalid

@Amaz1 
@catninja- 
@Oussamarer 
@Flipsels

**Comment by Amaz1** [comment]
:+1:
