### ISSUE TITLE
Mapgen stuff!

### ISSUE THREAD

**Issue by Amaz1** [minetest-LOTT/Lord-of-the-Test#23]
I have made four new branches, three of which add a new feature, one of which fixes the code. Have a play around with them, and tell me which ones you think should be merged! The indentation one has the other commits with it in its branch, because otherwise it would require a lot of work.*
So, have a play with them, and tell me what you think!

*Actually, it was a mistake.

**Comment by fishyWET** [comment]
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/133d5e392fadf176f6a13b314bf365edcc365e10
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/1145a59796bfa1762b61100089e550d34a587761
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/71eac26c7cdeaac0ea928d84de83e6271268527d
