### ISSUE TITLE
Here are the known problems

### ISSUE THREAD

**Issue by narrnika** [minetest-LOTT/Lord-of-the-Test#36]
"...however there will be some bugs here and there so please report them."
Ok. Here are the known problems:

- [x] 1) in lottpotion/potionbrewing.lua [str. 160-162] and lottinventory/potions.lua [str. 66, 72, 78] lottmobs:spiderpoison - unknown item;

- [x] 2) lottinventory/potions.lua [str. 12, 18, 24] vessels:glass_bottle, but in lottpotion/potionbrewing.lua [str. 151-153] lottpotion:glass_bottle_water;

- [x] 3) in lottmapgen/schems/*.we old version lottpotion:brewer & lottpotion:potion_brewer formspec, may be remove meta from *.we?

- [ ] 4) in lottarmor/textures/ are missing *_preview.png for boots_copper, helmet_copper, helmet_galvorn, helmet_silver, leggings_copper, leggings_silver, shield_bronze, shield_copper, shield_galvorn, shield_gold, shield_mithril, shield_silver, shield_steel, shield_wood;

- [x] 5) when rightclick second trader - "Stopping server... /lottmobs/trader.lua:223: attempt to concatenate field 'game_name' (a nil value)", may be string 223-238 put in "if self.game_name ~= nil then .. end"?

P.S. I'm sorry, my english - is google-translate.

**Comment by Amaz1** [comment]
Thanks for this, I'll have a look and see if I can fix them!

**Comment by Amaz1** [comment]
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/815e425e0b09d901719a11dec012d23ac3a692c8
Fixes 5

**Comment by narrnika** [comment]
"Is it alright for me to use things from your repository (https://github.com/narrnika/L.O.R.D) to fix these issues?" - оh, yes, of course, you can use them; but this temporal textures, and then I'll update them, may be.

**Comment by Amaz1** [comment]
Thank you very much! 
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/924c6bd8aef04b1c4f7b573295b4969285b6bc7e

I think that fixes all of these bugs you've found so far!
If/when you find any more, feel free to either reopen this issue (If you can) or make a new one!
