### ISSUE TITLE
 typo

### ISSUE THREAD

**Issue by narrnika** [minetest-LOTT/Lord-of-the-Test#37]
mods/lottblocks/decoration.lua [72]:
grups -> groups
else oddly_breakable_by_hand=2 don't work.

**Comment by Amaz1** [comment]
Thank you!
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/dbe83d3db2c2cc4350ea8955a8ae7800e06e91db

**Comment by narrnika** [comment]
mods/lottores/init.lua
string 1151
stairs.register_stair_and_slab("tin_block", "lottores:galvorn_block",
probably should be so:
stairs.register_stair_and_slab("galvorn_block", "lottores:galvorn_block",
