### ISSUE TITLE
misprints

### ISSUE THREAD

**Issue by narrnika** [minetest-LOTT/Lord-of-the-Test#38]
**1. mods/lottores/init.lua [line 1151]**
`stairs.register_stair_and_slab("tin_block", "lottores:galvorn_block",`
probably should be so:
`stairs.register_stair_and_slab("galvorn_block", "lottores:galvorn_block",`

**2. mods/bones/init.lua [lines 88-90]**
It seems must be so (otherwise the timer doesn't change anything):
`else`
`	meta:set_int("time", time)`
`	return true`
`end`

*P.S. I'm sorry, my english - is google-translate.*

**Comment by Amaz1** [comment]
Thanks!
