### ISSUE TITLE
Image not loading for human players

### ISSUE THREAD

**Issue by agwilt** [minetest-LOTT/Lord-of-the-Test#39]
I just get this:

`ERROR[main]: generateImage(): Could not load image "men_skin.png" while building texture
 ERROR[main]: generateImage(): Creating a dummy image for "men_skin.png"
`

**Comment by narrnika** [comment]
*Really, I forgot to tell you about it when corrected in my fork.
Also, you still have confusion*:
**[mods/lottclasses/init.lua](https://github.com/minetest-LOTT/Lord-of-the-Test/blob/master/mods/lottclasses/init.lua)**
*in line 343:*
`player_race_stuff("`**men**`", "`**man**`", "male", give_stuff_man, name, privs, player)`
*must be, probably, as in line 355:*
`player_race_stuff("`**man**`", "`**men**`", "female", give_stuff_man, name, privs, player)`
*and in line 357 probably:*
`player_race_stuff("orc", "`**orc**`", "female", give_stuff_orc, name, privs, player)`
*must be as in line 345:*
`player_race_stuff("orc", "`**orcs**`", "male", give_stuff_orc, name, privs, player)`

*P.S. I'm sorry, my english - is google-translate.*

**Comment by agwilt** [comment]
Yeah, I sent a pull request (#40). I didn't catch the orc line, though ..

**Comment by agwilt** [comment]
OK, I updated the pull request. It should fix everything now.

**Comment by Amaz1** [comment]
Thanks!
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/6e2331fe8f900635aed759365c95167f16f03ce3
