### ISSUE TITLE
Clothes aren't updated on the player model

### ISSUE THREAD

**Issue by agwilt** [minetest-LOTT/Lord-of-the-Test#41]
I don't know what is happening internally, but new clothes chosen after commit 233c3ee3500a82b190caa4b6c11ebb854263630d don't appear on the player model.

**Comment by Amaz1** [comment]
Fixed!
Thanks for finding this...
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/9ee1e6e342f9812b7e4ee1248611d8535a5db56e
