### ISSUE TITLE
Races don't work on server admins

### ISSUE THREAD

**Issue by agwilt** [minetest-LOTT/Lord-of-the-Test#42]
When you start a new server, your player doesn't get the racer chooser popup, and defaults to dwarf. This is because server admins automatically have *all* privileges, including `GAMEdwarf`, `GAMEelf`, etc. ...

And because `GAMEdwarf` is checked first, they always default to a dwarf, but the race chooser is never displayed.

I'm not sure if there is a proper solution, but what about a hidden "wizard" identified by the `server` privilege. Then the server admin has a race and a pretty kick-ass one, too.

**Comment by Amaz1** [comment]
Yeah, that is a problem.

The wizard solution sounds awesome though.

**Comment by agwilt** [comment]
I made a [wizard-race](https://github.com/agwilt/Lord-of-the-Test/tree/wizard-race) branch on my fork with a rough implementation. I might try to make some wizardy clothes and possibly a staff too :)

The only problem is that new admin players don't get default items, because they already have all the privs. On the other hand, the admin shouldn't find it hard to just `/giveme` stuff when needed ...

**Comment by Amaz1** [comment]
Fixed!
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/72a3a82fbfda8e121a325cf06700df7b861a5e48
