### ISSUE TITLE
lorienhouse - infinite generation

### ISSUE THREAD

**Issue by narrnika** [minetest-LOTT/Lord-of-the-Test#45]
[mods/lottmapgen/schematics.lua] (https://github.com/minetest-LOTT/Lord-of-the-Test/blob/master/mods/lottmapgen/schematics.lua)
*in minetest.register_abm for remove_node (lines 229 - 245) are missing "lottmapgen:lorienhouse"*

**Comment by agwilt** [comment]
Like this? https://github.com/minetest-LOTT/Lord-of-the-Test/pull/46

**Comment by fishyWET** [comment]
https://github.com/minetest-LOTT/Lord-of-the-Test/commit/f03b621b17e59aaa50dd6cfd7f5dbb2cce6f48e7
