### ISSUE TITLE
the game quits suddenly (Solved)

### ISSUE THREAD

**Issue by juanpedro1981** [minetest-LOTT/Lord-of-the-Test#50]
This often occurs when it appears some member of a race.
I use Linux Mint ; AMD dual core 4Gb ram
I like this game :) Thanks

http://pastebin.com/raw/Lgs8H3g8
(Post is edited for easier viewing of error logs)

**Comment by badtoad2000** [comment]
I don't see any reference p or dist around lines 470-471 in the current version of mobs/api.lua, so you may old version of the game. You might want to update your copy of the game, and see.
If you had not used git to get the games previously, you can delete or move /usr/share/minetest/games/Lord-of-the-Test and git the latest.

cd /usr/share/minetest/games
git clone git://github.com/minetest-LOTT/Lord-of-the-Test

or if you used git previously:
cd /usr/share/minetest/games/Lord-of-the-Test
git pull

Hopefully this helps.

**Comment by badtoad2000** [comment]
I notice you have the games in /usr/share, and for me that would require using sudo to update. However, minetest (compiled with  "cmake . -DRUN_IN_PLACE=FALSE" which it appears yours is), will look for games and mods in ~/.minetest (which is more convenient to update). If you mods and games were there, and you used git clone ... to download them, then you could use something like the following to update them (easiest to put this in a little executable file):

for i in `ls -1d ~/.minetest/mods/* ~/.minetest/games/*`
do
   if [[ -e $i/.git ]]
   then
      cd $i
      git pull
   fi
done

**Comment by agwilt** [comment]
Or just make a .deb for the mod, like my [AUR Arch packages](https://aur.archlinux.org/packages/?SeB=m&K=MadTux) :stuck_out_tongue:

**Comment by badtoad2000** [comment]
Yes, but given that his version is at least 3-months out of date, I thought it would be good to give him the script. He could then set up a cron to update the games/mods on a weekly basis, or just manually execute it periodically (hopefully issues fixed will exceed those added).

It doesn't show, but in my previous comment there should be a "left-quote" (same key as the "~") before the ls and at the end of that line (after the last *).

**Comment by Amaz1** [comment]
@juanpedro1981 What Minetest version are you running?
Also, as badtoad2000 suggested, I recommend that you install LOTT in .minetest, as it's easier to update. (You might need to use ctrl+h to show hidden files.)

**Comment by juanpedro1981** [comment]
I'm running Minetest 0.4.13. I don't used git previously, yes now. 
Now is different, plants moving with the wind. I test the game and I will confirm.

**Comment by juanpedro1981** [comment]
I am among the ents and the game not closed. It work! Thanks for your help. I will learn more about git.
Solved with this:
cd /usr/share/minetest/games
git clone git://github.com/minetest-LOTT/Lord-of-the-Test
Thanks again.
